### ISSUE TITLE
Depenizen builds 402 and up crash on Paper when Bungee socket enabled

### ISSUE THREAD

**Issue by PsychoLynx** [DenizenScript/Depenizen#209]
Hello!

I tried running the latest Depenizen build (408) with latest Paper (b1474) and Waterfall (b181) which unfortunately leads into an error with Depenizen disabling itself on the Paper side of things - but only when the bungee socket is enabled. When the socket is disabled, Depenizen starts up without errors.

LOG: https://pastebin.com/5QurnLp5

In my tests, the last build of Depenizen that works on Paper&Waterfall without errors  on startup (using the exact same config) is build 397. Builds up to 401 have the following error, but allow Depenizen to start up: https://pastebin.com/d07nDw3Y

With latest Spigot and Bungeecord, the same IncompatibleClassChangeError persists, but Depenizen doesn't disable.

I hope this helps in debugging, please ask if you want any more info.

**Comment by mcmonkey4eva** [comment]
All recent versions of Depenizen (402+) are built for the latest Denizen experimental dev builds at http://ci.citizensnpcs.co/job/Denizen_Developmental/
Depenizen build 398 included a PR that randomly throws errors due to poor coding on the PR author's part - specifically https://github.com/DenizenScript/Depenizen/pull/193 by @Mwthorn 
They've been fixed in the more recent builds (by way of improving the support handler infrastructure to not have that broken code be loaded in the first place to have the chance of throwing errors)

If you're using Denizen stable builds: use Depenizen build 397
If you're using Denizen dev experimental builds: use Depenizen latest, also be around on Discord at https://discord.gg/Q6pZGSR to discuss any issues with the dev builds.
