### ISSUE TITLE
Support for MMOItems

### ISSUE THREAD

**Issue by ntall1** [DenizenScript/Depenizen#228]
It would be great if you could add support for the plugin MMOItems. https://www.spigotmc.org/resources/mmoitems-40-stats-30-abilities-item-edition-gui.39267/

Tags like:
i@item.is_mmoitem - is mmoitem true of false
i@item.mmoitem_type - return mmo item type e.g. hammer, gem_stone, greataxe
i@item.mmoitem_name - return the name of the mmo item (not the display name of the item)
i@item.mmoitem_display_name - return the display name of an mmoitem

Thanks.

**Comment by Indyuce** [comment]
Hey, PM me on Discord, I'll give you the jar and methods to get that item info
Indyuce#3058

**Comment by MusicScore** [comment]
That's really not the issue. The issue is that any contributing developer would have to purchase the JAR to do any testing, and even then a premium plugin typically does not have a reliable API or any open-source code for them to reference.

If there is a free or open-source version of the plugin, then there can be support for it. Otherwise, attempting to support a premium plugin is limited or nonexistent by nature.

**Comment by mcmonkey4eva** [comment]
We can not support premium plugins as @MusicScore explained above.

Extra bit of reference on that: any project we build against (say, a plugin jar) by necessity must have a public file for the build server to use. In cases where a plugin is available but not distributed via Maven, we upload a copy of the original jar ourselves directly to the Git repo.
