### ISSUE TITLE
Fundamental Loading Error

### ISSUE THREAD

**Issue by robgob** [DenizenScript/Depenizen#280]
Hello all,
I am getting this "Fundamental Loading Error" when Depenizen goes to bridge the plugins on load. It is failing to load EssentialsX, WorldGaurd, and Factions. I updated everything to the latest version.. :x

Does this mean the new versions of these plugins has broken Depenizen or something else..

###  **- Versions -**
**Spigot:** CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Citizens:**  Citizens version 2.0.25-SNAPSHOT (build 1760)
**Denizen:** 1.1.0-SNAPSHOT (build 1688-REL), core version: 1.50-SNAPSHOT (Build 394)
**Sentinel:** Sentinel version 1.9.5 (build 301)
**Depenizen:** Depenizen version 2.0.0 (build 539)
**EssentialsX:** Essentials version 2.17.1.0
**WorldGuard:** WorldGuard 7.0.1-rc2
**Factions:** Version: 3.2.3

**Latest Log:** https://pastebin.com/3mWvkJpx

Thank you!

**Comment by mcmonkey4eva** [comment]
Grab an older build of Depenizen or the latest dev build of Denizen.
Mix-n-match versions don't work. (You're running the release build of Denizen, which is a bit behind due to dev builds being slightly unstable)

This is the Depenizen build to match the release build of Denizen: https://ci.citizensnpcs.co/job/Depenizen/535/
