### ISSUE TITLE
Bungee Issues

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Depenizen#283]
For some reason server can occasionally lose connection with Depenizen Bungee and throw this error (on the bungee proxy) when trying to reconnect:
Invalid FIRST packet id (must be MyInfoPacket): 0

This happens randomly(?) over time, or when restarting many servers and the bungee proxy at once. It's hard to pin down a specific trigger. It can happen in a day, in a week, or not at all, and only happens to some servers, but can happen to any of them.

**Comment by mcmonkey4eva** [comment]
Please post:
- Spigot version
- Denizen version
- Depenizen version
- DepenizenBungee version
- Bungee version

**Comment by Ph4i1ur3** [comment]
Server versions range from 1.12.2 to 1.14.4 All using the latest paper builds available.
1.12.2 - paper-1618
1.13.2 - paper-651
1.14.4 - paper-223
Denizen versions are all 1689 (latest release)
Depenizen build: 540
Depenizen Bungee Build: 2.0.0-b12
Bungee: (Paper) Waterfall build-296

**Comment by Ph4i1ur3** [comment]
Will do.

**Comment by Ph4i1ur3** [comment]
Closing for now, will report back if issue can be reproduced on supported software.

**Comment by Ph4i1ur3** [comment]
Can confirm this issue still persists using the latest build of BungeeCord.

**Comment by mcmonkey4eva** [comment]
Would really need some way to replicate it before being able to do anything about this...

**Comment by Ph4i1ur3** [comment]
As this issue can take days to appear, I'm not sure this issue is easily reproducible. I have been unsuccessful in my attempts to force the error.

**Comment by mcmonkey4eva** [comment]
For the sake of determining priority + narrowing possible causes:
Does this error:
A: _Appear in console_ but otherwise things continue to function (ie it then reconnects again and works)
B: _Loop in console_ and things break (ie it's broken til a restart and loading console), or
C: _Appear once and break_ (ie, broken til restart, but doesn't show again in console)

**Comment by Ph4i1ur3** [comment]
The error is looping, and only fixes if I stop ever server in the network, then the bungee proxy, boot the bungee proxy, and then the servers.

If i do things in any other order, the issue can persist on *some* servers.

**Comment by PsychoLynx** [comment]
I have had similar issues for a while - in my experience it seems to happen when players attempt to log in and they trigger "on bungee player joins network"-event in our custom login script.

**Comment by Ph4i1ur3** [comment]
I have no scripts utilizing the above posted event (or any bungee event, outside of the ping event, as stated in my other issue, and we just started using that today.), we do however make liberal usage of the various bungee commands available, so data is traveling over the proxy very frequently.

**Comment by mcmonkey4eva** [comment]
https://github.com/DenizenScript/Depenizen/commit/5a69e0293b7c59f9bf873a68b49dae94350f5b6c might help with this. Hard to say given lack of ability to replicate + the error source being a bit unclear.

The issue _sounds_ like it could be an async out-of-order screwup, which if so that commit should fix by refusing to send any additional packets until the MyInfo packet is sent. It's possible it will simply replace the first error with a different one (likely on the Spigot server's side).
Will have to see if y'all can hit this issue again on the new build

**Comment by Ph4i1ur3** [comment]
Issue seems to have been resolved, will re-open if this changes.

**Comment by PsychoLynx** [comment]
It seems to be much better now at least. I only had the connection crap out once during the time - I set up some debug flags on the proxy in case it happens again.
