### ISSUE TITLE
Shopkeeper integration: isUIActive

### ISSUE THREAD

**Issue by blablubbabc** [DenizenScript/Depenizen#331]
I noticed this by coincidence while looking through the code: https://github.com/DenizenScript/Depenizen/blob/master/src/main/java/com/denizenscript/depenizen/bukkit/objects/shopkeepers/ShopKeeperTag.java#L173

The purpose of this seems to have a flag for whether a shopkeeper is currently trading with a player. However, the used isUIActive attribute is not actually reflecting that (instead this is about temporarily disabling an UI if it is about to get closed within the next tick).

To check if some player is currently trading with a shopkeeper one would probably have to check for all online players if one of them has an 'active UI session' (using https://github.com/Shopkeepers/Shopkeepers/blob/master/src/api/java/com/nisovin/shopkeepers/api/ui/UIRegistry.java#L13) of  type 'editor' (https://github.com/Shopkeepers/Shopkeepers/blob/master/src/api/java/com/nisovin/shopkeepers/api/ui/DefaultUITypes.java#L23) with a non-null shopkeeper matching the currently inspected shopkeeper (https://github.com/Shopkeepers/Shopkeepers/blob/master/src/api/java/com/nisovin/shopkeepers/api/ui/UISession.java#L7).

**Comment by mcmonkey4eva** [comment]
That's using `isUIActive()` because it's a tag named `is_ui_active` - I guess @Fortifier42 decided to expose that boolean directly to scripts when adding initial Shopkeeper compat 4 years ago @ https://github.com/DenizenScript/Depenizen/commit/651b024c55aef1961b7cc2b249247f1b959994ce
Presumably he just took a guess at what it did when writing the meta doc there.

I fixed the doc per your description of what it actually does.
