### ISSUE TITLE
Quests NoSuchMethodError

### ISSUE THREAD

**Issue by Curtis73** [DenizenScript/Depenizen#359]
Hey, I'm getting the following error whenever I try using `player.quests.completed_names`: https://pastebin.com/PZV3HpET
I recently updated to Quests 4.0 so I believe the issue's related to that in some way
Thank you!

**Comment by BehrRiley** [comment]
It'd be a much better idea to ask this kind of question on the support channel for Denizen in our Discord: https://discord.gg/Q6pZGSR

When you do, please instead of a snippet of your console, help us help you by pasting your script to https://paste.denizenscript.com/New/Script, and properly debug the script using the debugging commands. To share a debug log quickly and easily with helpers, simply run the command `/denizen debug -r` in-game to begin recording, then run through the part of the script you need help with, then run the command `/denizen submit`. Please provide both of those links on the Discord channel.
